apiVersion: v1
kind: Service
metadata:
  name: mechwiz-service
spec:
  type: NodePort
  selector:
    app: mechwiz
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30007

---

apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30090
  selector:
    app: prometheus


---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30030
  selector:
    app: grafana  

